api_url: http://reference.craigslist.org/Areas

searches:
  - area: sfbay
    category: cta
    term: 2020 honda accord
   
  #- area: seattle
  #  category: cta
  #  term: toyota

  #- area: chico
  #  category: cta
  #  term: hellcat

  #- area: bleh
  #  category: cta
  #  term: hellcat

