api_url: http://reference.craigslist.org/Areas

searches:
  - area: sfbay
    category: cta
    term: honda
   
  - area: seattle
    category: cta
    term: toyota

  - area: chico
    category: cta
    term: hellcat

  - area: bleh
    category: cta
    term: hellcat

